CREATE TABLE IF NOT EXISTS worker (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),
    BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > 1900),
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK (SALARY >= 100 AND SALARY <= 100000)
    );

CREATE TABLE IF NOT EXISTS client (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
    );

CREATE TABLE IF NOT EXISTS project(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID BIGINT NOT NULL,
    START_DATE DATE,
    FINISH_DATE DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
    );

CREATE TABLE IF NOT EXISTS project_worker(
    PROJECT_ID BIGINT NOT NULL,
    WORKER_ID BIGINT NOT NULL,
    PRIMARY KEY (PROJECT_ID,WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
    );

